# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

install! 'cocoapods',
  share_schemes_for_development_pods: true,
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true
  
target 'UsingSPMFromCPDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UsingSPMFromCPDemo
  pod "FeatureA", path: "libraries/FeatureA"

  target 'UsingSPMFromCPDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UsingSPMFromCPDemoUITests' do
    # Pods for testing
  end

end

post_integrate do |installer|

  # FeatureB
  featureB_dependant = ["FeatureA"]

  puts "Injecting FeatureB SPM framework into ..."
  featureB_dependant.each do |project|
      puts "  #{project}"
      `swift run --package-path libraries XcodeSPMI addLocal --project-path Pods/#{project}.xcodeproj --spm-path ../libraries/ --product FeatureB --target-name #{project}`
  end
end